# name: Vercel Production Deployment

# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# on:
#   push:
#     branches:
#       - main

# jobs:
#   Deploy-Production:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Yarn
#         run: npm install --global yarn

#       - name: Install Dependencies
#         run: yarn install

#       - name: Install Vercel CLI
#         run: yarn global add vercel

#       - name: Deploy to Vercel
#         env:
#           VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#           VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#         run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
